spring.application.name=blogging-platform-api

spring.datasource.url=<location>
spring.datasource.username=<user>
spring.datasource.password=<pass>
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
