spring.application.name=blogging-platform-api

spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=Rafraf
spring.datasource.password=Shortpass123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
