CREATE TABLE IF NOT EXISTS blogs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(100) UNIQUE,
    content TEXT,
    category TEXT,
    tags TEXT[],
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    PRIMARY KEY(id)
);